import { css } from "../../../styled-system/css";

export const comboboxStyles = () => ({
  control: css({
    display: "inline-flex",
    justifyContent: "space-between",
    width: "200px",
    borderRadius: "6px",
    fontSize: "16px",
    lineHeight: "1",
    outline: "none",
    backgroundColor: "white",
    border: "1px solid hsl(240 6% 90%)",
    color: "hsl(240 4% 16%)",
    transition: "border-color 250ms, color 250ms",
    _invalid: {
      borderColor: "hsl(0 72% 51%)",
      color: "hsl(0 72% 51%)",
    },
  }),
  controlMulti: css({
    flexWrap: "wrap",
  }),
  inputContainer: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.25rem",
    flex: "1",
  }),
  input: css({
    appearance: "none",
    display: "inline-flex",
    minWidth: "0",
    minHeight: "40px",
    paddingLeft: "16px",
    fontSize: "16px",
    background: "transparent",
    borderTopLeftRadius: "6px",
    borderBottomLeftRadius: "6px",
    outline: "none",
    border: "none",
    _placeholder: {
      color: "hsl(240 4% 46%)",
    },
  }),
  trigger: css({
    appearance: "none",
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    width: "auto",
    outline: "none",
    borderTopRightRadius: "6px",
    borderBottomRightRadius: "6px",
    padding: "0 10px",
    backgroundColor: "hsl(240 5% 96%)",
    borderLeft: "1px solid hsl(240 6% 90%)",
    color: "hsl(240 4% 16%)",
    fontSize: "16px",
    lineHeight: "0",
    transition: "250ms background-color",
    border: "none",
  }),
  clearButton: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    w: "1.5rem",
    h: "1.5rem",
    bg: "transparent",
    border: "none",
    borderRadius: "selector",
    cursor: "pointer",
    flexShrink: "0",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.200",
    },
  }),
  tag: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "0.25rem",
    px: "0.5rem",
    py: "0.125rem",
    bg: "secondary",
    color: "content.secondary",
    fontSize: "0.75rem",
    fontWeight: "medium",
    borderRadius: "selector",
    flexShrink: "0",
  }),
  tagButton: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    w: "1rem",
    h: "1rem",
    bg: "transparent",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.content",
      opacity: "0.2",
    },
  }),
  content: css({
    position: "absolute",
    zIndex: "50",
    w: "full",
    maxW: "xs",
    bg: "base.100",
    borderRadius: "box",
    boxShadow: "lg",
    border: "default",
    p: "0.25rem",
    mt: "0.25rem",
    animation: "fadeIn 0.15s ease-in-out",
    _closed: {
      animation: "fadeOut 0.15s ease-in-out",
    },
  }),
  listbox: css({
    maxH: "20rem",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
  }),
  item: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: "selector",
    px: "0.75rem",
    py: "0.5rem",
    fontSize: "0.875rem",
    cursor: "pointer",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.200",
    },
    _highlighted: {
      bg: "primary",
      color: "content.primary",
    },
    _selected: {
      fontWeight: "medium",
    },
    _disabled: {
      opacity: "0.5",
      cursor: "not-allowed",
    },
  }),
  itemIndicator: css({
    ml: "0.5rem",
    opacity: "0",
    transition: "opacity 0.15s ease-in-out",
    _selected: {
      opacity: "1",
    },
  }),
  icon: css({
    height: "20px",
    width: "20px",
    flex: "0 0 20px",
  }),
  description: css({
    fontSize: "0.875rem",
    color: "base.content",
    opacity: "0.7",
    mt: "0.5rem",
  }),
  errorMessage: css({
    fontSize: "0.875rem",
    color: "error",
    mt: "0.5rem",
    display: "none",
    _invalid: {
      display: "block",
    },
  }),
});
