import { css } from "../../../styled-system/css";

export const comboboxStyles = () => ({
  control: css({
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    height: "auto",
    minHeight: "2.5rem",
    py: "0.25rem",
    px: "0.5rem",
    bg: "base.200",
    border: "default",
    borderRadius: "field",
    transition: "all 0.2s ease-in-out",
    _focusWithin: {
      borderColor: "primary",
      outline: "1px solid {colors.primary}",
      outlineOffset: "-1px",
    },
    _invalid: {
      borderColor: "error",
    },
  }),
  controlMulti: css({
    flexWrap: "wrap",
  }),
  inputContainer: css({
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    gap: "0.25rem",
    flex: "1",
  }),
  input: css({
    flex: "1",
    minWidth: "0",
    bg: "transparent",
    border: "none",
    outline: "none",
    px: "0.5rem",
    py: "0.25rem",
    color: "base.content",
    _placeholder: {
      color: "base.content",
      opacity: "0.5",
    },
    _focus: {
      outline: "none",
    },
  }),
  trigger: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    w: "2rem",
    h: "2rem",
    bg: "transparent",
    border: "none",
    borderRadius: "selector",
    cursor: "pointer",
    flexShrink: "0",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.200",
    },
  }),
  clearButton: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    w: "1.5rem",
    h: "1.5rem",
    bg: "transparent",
    border: "none",
    borderRadius: "selector",
    cursor: "pointer",
    flexShrink: "0",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.200",
    },
  }),
  tag: css({
    display: "inline-flex",
    alignItems: "center",
    gap: "0.25rem",
    px: "0.5rem",
    py: "0.125rem",
    bg: "secondary",
    color: "content.secondary",
    fontSize: "0.75rem",
    fontWeight: "medium",
    borderRadius: "selector",
    flexShrink: "0",
  }),
  tagButton: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    w: "1rem",
    h: "1rem",
    bg: "transparent",
    border: "none",
    borderRadius: "50%",
    cursor: "pointer",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.content",
      opacity: "0.2",
    },
  }),
  content: css({
    position: "absolute",
    zIndex: "50",
    w: "full",
    maxW: "xs",
    bg: "base.100",
    borderRadius: "box",
    boxShadow: "lg",
    border: "default",
    p: "0.25rem",
    mt: "0.25rem",
    animation: "fadeIn 0.15s ease-in-out",
    _closed: {
      animation: "fadeOut 0.15s ease-in-out",
    },
  }),
  listbox: css({
    maxH: "20rem",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: "0.125rem",
  }),
  item: css({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: "selector",
    px: "0.75rem",
    py: "0.5rem",
    fontSize: "0.875rem",
    cursor: "pointer",
    transition: "all 0.15s ease-in-out",
    _hover: {
      bg: "base.200",
    },
    _highlighted: {
      bg: "primary",
      color: "content.primary",
    },
    _selected: {
      fontWeight: "medium",
    },
    _disabled: {
      opacity: "0.5",
      cursor: "not-allowed",
    },
  }),
  itemIndicator: css({
    ml: "0.5rem",
    opacity: "0",
    transition: "opacity 0.15s ease-in-out",
    _selected: {
      opacity: "1",
    },
  }),
  icon: css({
    w: "1rem",
    h: "1rem",
    flexShrink: "0",
  }),
  description: css({
    fontSize: "0.875rem",
    color: "base.content",
    opacity: "0.7",
    mt: "0.5rem",
  }),
  errorMessage: css({
    fontSize: "0.875rem",
    color: "error",
    mt: "0.5rem",
    display: "none",
    _invalid: {
      display: "block",
    },
  }),
});
